server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/becarrillo/Gavasoft-microservices-config.git
          clone-on-start: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    defaultZone: http://gavasoftregistryservice.railway.internal:8761/eureka/